version: 0.2

env:
  secrets-manager:
    NAME: name
    POSTGRES_USER: user
    PASSWORD: password
    HOST: host
    AWS_ACCESS_KEY_ID: access_key_id
    AWS_SECRET_ACCESS_KEY: secret_key
    AWS_STORAGE_BUCKET_NAME: bucket_name

  plaintext:
    AWS_STORAGE_BUCKET_NAME : scalable-static
    AWS_S3_REGION_NAME : eu-west-1

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - cp /eventshark/.env /eventsharkbuild/
      - echo Collecting static files...
      - python manage.py collectstatic --no-input

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
      - python3 manage.py test

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes
